CREATE QUEUE [dbo].[ProductionQueue] WITH STATUS = ON,
RETENTION = OFF
ON [PRIMARY]
GO

CREATE EVENT NOTIFICATION [ProductionEventNotification]
ON QUEUE [dbo].[ProductionQueue]
FOR BROKER_QUEUE_DISABLED
TO SERVICE 'ProductionService', '104BD1E5-5729-481C-818B-04C0E3216E68'
GO